#!/usr/bin/env python3
# This file is placed in the Public Domain.


"clean"


import os


cwd = os.getcwd()


SKIPDIR = [".git", ".pytest_cache", "env"]


def popen(txt, silent=False):
    for line in os.popen(txt).readlines():
        if silent:
            continue
        print(line.strip())


def main():
    popen("rm -fR build dist MANIFEST *.egg-info")
    popen("rm -fR  __pycache__ *~")
    popen("rm -fR .test .opr .opq")
    popen("din/loop . rm -fR *~")
    popen("din/loop . rm -fR __pycache__")


if __name__ == "__main__":
    main()
