#!/usr/bin/env python3
# This file is placed in the Public Domain.


"loop"


import os
import sys


SKIP = ["env"]


def loop(path, txt):
    old = os.getcwd()
    os.chdir(path)
    for fnn in os.listdir(path):
        if fnn in SKIP:
            continue
        old = os.getcwd()
        fpath = os.path.abspath(os.path.join(path, fnn))
        if os.path.isdir(fpath):
            loop(fpath, txt)
        if not os.path.isdir(fpath):
            continue
        os.chdir(fpath)
        popen(txt)
        os.chdir(old)
        #os.chdir("..")
    os.chdir(old)


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.rstrip())
        sys.stdout.flush()


if __name__ == "__main__":
    if not len(sys.argv) >= 3:
        print("loop <dir> <cmd>")
    else:
        loop(sys.argv[1], " ".join(sys.argv[2:]))
