#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.strip())


popen("din/clean")
popen("rm -fR env")
