#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import sys


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.strip())
        sys.stdout.flush()


popen("grep -R print")
